on: push
name: ShellCheck
jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: shellcheck
      uses: actions/bin/shellcheck@master
      with:
        args: wireguard-server.sh -e SC1091 -e SC2034
